#!/bin/bash
uid=$1
dir=$2

names="etc/alternatives etc/emacs etc/emacs23"
for name in $names; do
    if [ -d "/$name" ]; then
        mkdir $dir/$name
        mount --bind /$name $dir/$name
    fi
done
